name: Publicar Pagina a Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: configura nodejs  
        uses: actions/setup-node@v3
        with:
            node-version: '18' 

      - name: Instala Surge       
        run: npm install --global surge

      - name: Publicar pagina
        run: surge --project ./ --domain Codeweb --token 4fc2b5dc46d477fd19e350d3a41d4134
